#!/usr/bin/env python3
"""
build_SUMMARY.py   (revision-2 final assembly)

Generates runs/revision2/SUMMARY.md: every number produced by the revision,
labelled with the manuscript location it belongs in, and the index of
paste-ready fragments.

Like build_SI.py, every value is read from a named file. The manuscript
LOCATIONS are the editorial mapping and are stated here in one place, so that
if the table numbering changes it changes in exactly one file.

    PYTHONHASHSEED=0 python3 build_SUMMARY.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

R2 = Path("runs/revision2")
CONS = Path("runs/rceg_final_consolidated")
OUT = R2 / "SUMMARY.md"

# Final manuscript table numbering, per the author's directive. The revision-2
# working files were named under an EARLIER numbering and do not match: see the
# "filename trap" note below and DISCREPANCIES.md.
TABLES = {
    1: "Corpus composition",
    2: "Confidence bins",
    3: "Recompute convergence",
    4: "Calibration by domain",
    5: "Chemical domains",
    6: "Ablation",
    7: "Per-domain performance",
    8: "Split protocols",
    9: "Computational cost",
}


def read(path: Path) -> pd.DataFrame:
    if not path.exists():
        sys.exit(f"MISSING REQUIRED INPUT: {path}")
    return pd.read_csv(path)


def main() -> None:
    L: list[str] = []
    add = L.append

    fa = read(CONS / "frozen_architecture.csv").iloc[0]
    abl = read(R2 / "B3_ablation.csv").set_index("config")
    dom = read(R2 / "B2_table3.csv")
    b4 = read(R2 / "B4_table5.csv")
    ind = read(R2 / "B4_domain_independence_test.csv")
    off = read(CONS / "calibration_offsets.csv").iloc[0]
    sp = read(R2 / "B5_split_protocols.csv").set_index("split_mode")
    b6 = read(R2 / "B6_summary.csv").set_index("config")
    ext = read(R2 / "D1_external_metrics.csv")
    geo = read(CONS / "geometry_sensitivity.csv")
    ok = geo[geo.converged == True]          # noqa: E712
    ga = ok.delta_gap.abs()
    cf = read(R2 / "C2_conformer_floor.csv").iloc[0]
    t9 = read(R2 / "C3_timings.csv")
    cl = read(R2 / "A2_cleaning_counts.csv")
    rec = read(R2 / "A1_recompute_reconciliation.csv")
    rec = rec[~rec.domain.astype(str).str.upper().eq("TOTAL")]
    names = read(R2 / "A4_lasso_feature_names.csv")
    leak = read(R2 / "A5_leakage_audit.csv")
    osh = read(R2 / "A6_openshell_agreement.csv")
    a8 = read(R2 / "A8_dual_labelled.csv")
    corp = read(CONS / "corpus_composition.csv")

    def corpv(section, metric, group="all"):
        m = corp[(corp.section == section) & (corp.metric == metric) &
                 (corp.group == group)]
        if m.empty:
            sys.exit(f"corpus_composition missing {section}/{metric}/{group}")
        return float(m.value.iloc[0])

    dd = dom[dom.group_type == "domain"].sort_values("mae")
    best, worst = dd.iloc[0], dd.iloc[-1]
    mg = names.resolved_name.astype(str).str.startswith("MorganFP_")
    strict = ext[ext.evaluation == "strict_frozen_external"]
    cross = ext[ext.evaluation == "five_fold_crossfit_offset_aligned"]
    spread_ind = float(ind["mean"].max() - ind["mean"].min())

    # --------------------------------------------------------------- header
    add("# rCEG revision 2 — number-by-number summary")
    add("")
    add("Every measurement produced by this revision, with the manuscript "
        "location it belongs in and the file it came from. Numbers are stated "
        "here exactly as the result files hold them; where a number in the "
        "submitted manuscript disagrees, that is noted in the row and again "
        "in `DISCREPANCIES.md`.")
    add("")
    add("Generated by `build_SUMMARY.py`. Companion documents: "
        "`SUPPORTING_INFORMATION.md` (generated by `build_SI.py`) and "
        "`DISCREPANCIES.md`.")
    add("")

    # ------------------------------------------------------- filename trap
    add("> **Read this before opening any file.** The working files in this "
        "directory were named under an earlier table numbering and **do not "
        "match the final manuscript numbering**. Specifically: "
        "`B2_table3.csv` holds per-domain performance, which is manuscript "
        "**Table 7**; `B4_table5.csv` holds calibration by domain, which is "
        "manuscript **Table 4**. The filenames were left unchanged so that "
        "they still match the task IDs in the revision spec. Trust the "
        "mapping in this document, not the filenames.")
    add("")
    add("---")
    add("")

    # ------------------------------------------------------------ headline
    add("## 1. Headline result — Abstract, Results opening, Conclusions")
    add("")
    add("| Quantity | Value | Where it goes | Source |")
    add("|---|---|---|---|")
    add(f"| Test MAE, headline | **{fa.test_mae:.3f} ± {fa.test_sd:.3f} eV** | "
        "Abstract; Results §1; Conclusions | `frozen_architecture.csv` |")
    add(f"| Test R² | **{fa.test_r2:.3f}** | Abstract; Results §1 | "
        "`frozen_architecture.csv` |")
    add(f"| Validation MAE (selection criterion) | "
        f"{fa.val_mae:.3f} ± {fa.val_sd:.3f} eV | Methods, model selection | "
        "`frozen_architecture.csv` |")
    add(f"| Repeats | {int(read(R2/'B3_ablation.csv').n_repeats.max())} "
        "independent splits | Methods; every table caption | "
        "`B3_ablation.csv` |")
    add(f"| Selected configuration | `{fa.frozen_architecture}` | Methods | "
        "`frozen_architecture.csv` |")
    add("")
    add("**Selection was on validation, never on test.** "
        f"`{fa.frozen_architecture}` was chosen on validation MAE averaged "
        f"over the repeats, recorded verbatim in the frozen-architecture "
        f"file as: *{fa.why_not_domain_expert}*")
    add("")
    add(f"**The meta-learner was dropped.** *{fa.meta_learner_verdict}* The "
        "Introduction of the submitted draft still describes it as part of "
        "the architecture and must be rewritten — see `DISCREPANCIES.md`.")
    add("")
    add("---")
    add("")

    # ------------------------------------------------------------ Table 1/5
    add(f"## 2. Table {1} — {TABLES[1]}, and Table {5} — {TABLES[5]}")
    add("")
    add("| Quantity | Value | Source |")
    add("|---|---|---|")
    add(f"| Molecules in the strict corpus | "
        f"**{corpv('corpus','unique_canonical_smiles','strict_file'):,.0f}** | "
        "`corpus_composition.csv` |")
    add(f"| Records removed during cleaning | "
        f"**{int(cl['count'].sum()):,}** | `A2_cleaning_counts.csv` |")
    add(f"| Heavy atoms | median "
        f"{corpv('heavy_atoms','median'):.0f}, range "
        f"{corpv('heavy_atoms','min'):.0f}–{corpv('heavy_atoms','max'):.0f} "
        f"(5th–95th pct {corpv('heavy_atoms','p05'):.0f}–"
        f"{corpv('heavy_atoms','p95'):.0f}) | `corpus_composition.csv` |")
    add(f"| PQR gap | mean {corpv('gap_ev','mean'):.2f} eV, median "
        f"{corpv('gap_ev','median'):.2f} eV, SD {corpv('gap_ev','sd'):.2f} eV, "
        f"range {corpv('gap_ev','min'):.2f}–{corpv('gap_ev','max'):.2f} eV | "
        "`corpus_composition.csv` |")
    add("")
    add("**Domain populations (Table 5).**")
    add("")
    add("| Domain | n | % of corpus |")
    add("|---|---|---|")
    dc = corp[(corp.section == "domain") & (corp.metric == "domain_count") &
              (corp.group != "TOTAL")]
    tot = corpv("domain", "domain_count", "TOTAL")
    for _, r in dc.sort_values("value", ascending=False).iterrows():
        add(f"| `{r.group}` | {r.value:,.0f} | {100*r.value/tot:.1f}% |")
    add(f"| **total** | **{tot:,.0f}** | 100% |")
    add("")
    add("<sub>Source: `runs/rceg_final_consolidated/corpus_composition.csv`; "
        "`runs/revision2/A2_cleaning_counts.csv`</sub>")
    add("")
    add("---")
    add("")

    # ------------------------------------------------------------- Table 3
    add(f"## 3. Table {3} — {TABLES[3]}")
    add("")
    add(f"| Quantity | Value | Source |")
    add("|---|---|---|")
    add(f"| Molecules targeted for recomputation | "
        f"**{int(rec.n_targeted.sum())}** | `A1_recompute_reconciliation.csv` |")
    add(f"| Converged | **{int(rec.n_converged.sum())}** | same |")
    add(f"| Failed | **{int(rec.n_failed.sum())}** | same |")
    add("")
    add("Per-domain breakdown and failure modes: SI §S6.1. The apparent "
        "excess of failure records over final failures is retries, reconciled "
        "in the `n_records_that_later_converged` column.")
    add("")
    add("---")
    add("")

    # ------------------------------------------------------------- Table 4
    add(f"## 4. Table {4} — {TABLES[4]}")
    add("")
    add("Full table in SI §S2.1. The numbers the body text needs:")
    add("")
    add("| Quantity | Value | Where it goes | Source |")
    add("|---|---|---|---|")
    ovb = b4[b4.group == "all"].iloc[0]
    add(f"| Calibrated MAE, all domains | {ovb.mae:.3f} eV | Results, "
        "calibration | `B4_table5.csv` |")
    add(f"| Mean PQR − reference offset | {ovb.mean_pqr_minus_ref:.3f} eV "
        f"(SD {ovb.sd_pqr_minus_ref:.3f}) | Results, calibration | same |")
    add(f"| Per-domain offset range, held-out (val+test) | "
        f"{off.OFF_MIN:.3f} – {off.OFF_MAX:.3f} eV "
        f"(**spread {off.OFF_SPREAD:.3f} eV**) | Results; justification for "
        "per-domain calibration | `calibration_offsets.csv` |")
    add(f"| Per-domain offset range, single-partition file (superseded) | "
        f"{ind['mean'].min():.3f} – {ind['mean'].max():.3f} eV "
        f"(**spread {spread_ind:.3f} eV**) | same | "
        "`B4_domain_independence_test.csv` |")
    add("")
    add(f"⚠️ **Both of those are held-out numbers, not calibration-set "
        f"numbers.** {off.OFF_SPREAD:.3f} eV pools validation and test over "
        f"ten repeats; {spread_ind:.3f} eV comes from a single-partition file "
        "(n = 425) with no generating script, now superseded. The "
        "calibration-set spread over the same ten repeats is **1.637 eV**. "
        "Use `paste/C1_table4.md`, which gives both sets per class, and never "
        "average them.")
    add("")
    add("The substantive claim this supports: a single global offset would "
        "carry an error of order 1 eV in the domains at the ends of the "
        "range, several times the model's own error. That is why calibration "
        "is per-domain.")
    add("")
    add("---")
    add("")

    # ------------------------------------------------------------- Table 6
    add(f"## 5. Table {6} — {TABLES[6]}")
    add("")
    add("| Configuration | MAE ± SD (eV) | R² | Source |")
    add("|---|---|---|---|")
    for cfg in abl.sort_values("mae_mean").index:
        r = abl.loc[cfg]
        add(f"| `{cfg}` | {r.mae_mean:.3f} ± {r.mae_sd:.3f} | "
            f"{r.r2_mean:.3f} | `B3_ablation.csv` |")
    add("")
    add("The `domain_permuted` rows are the control: domain labels shuffled "
        "with sizes preserved, so only the chemical meaning of the partition "
        "is destroyed. Their degradation is the evidence that the "
        "architecture does chemical work rather than acting as an arbitrary "
        "ensemble.")
    add("")
    add("---")
    add("")

    # ------------------------------------------------------------- Table 7
    add(f"## 6. Table {7} — {TABLES[7]}")
    add("")
    add("| Domain | n | MAE (eV) | median abs err (eV) | RMSE | R² | Source |")
    add("|---|---|---|---|---|---|---|")
    order = ["qm9_like_small_organic", "near_qm9_larger_organic",
             "large_neutral_organic", "heteroatom_rich_non_qm9",
             "charged_or_radical"]
    dm = dom[dom.group_type == "domain"].set_index("group")
    for g in order:
        r = dm.loc[g]
        add(f"| `{g}` | {int(r.n)} | **{r.mae:.3f}** | "
            f"{r.median_abs_error:.3f} | {r.rmse:.3f} | {r.r2:.3f} | "
            "`B2_table3.csv` |")
    ao = dom[dom.group_type == "overall"].iloc[0]
    add(f"| **all** | {int(ao.n)} | {ao.mae:.3f} | "
        f"{ao.median_abs_error:.3f} | {ao.rmse:.3f} | {ao.r2:.3f} | same |")
    add("")
    add(f"⚠️ **Best domain: `{best.group}` at {best.mae:.3f} eV. Worst "
        f"domain: `{worst.group}` at {worst.mae:.3f} eV.** The submitted text "
        "names a different worst domain than the table shows; the table is "
        "right. See `DISCREPANCIES.md`.")
    add("")
    add("Error deciles per domain are in SI §S9, and they matter: the median "
        "absolute error is roughly half the MAE in every domain, because a "
        "small number of molecules carry very large errors. Quoting the "
        "median alongside the mean is the honest summary and is also more "
        "favourable to the model.")
    add("")
    add("---")
    add("")

    # ------------------------------------------------------------- Table 8
    add(f"## 7. Table {8} — {TABLES[8]}")
    add("")
    add("| Protocol | MAE ± SD (eV) | R² | n test | median max Tanimoto | "
        "Δ vs random |")
    add("|---|---|---|---|---|---|")
    base = sp.loc["random", "test_mae"]
    for m in ["random", "scaffold", "cluster"]:
        r = sp.loc[m]
        d = r.test_mae - base
        dl = "—" if m == "random" else f"{d:+.3f} ({100*d/base:+.1f}%)"
        add(f"| {m} | {r.test_mae:.3f} ± {r.test_mae_sd:.3f} | "
            f"{r.test_r2:.3f} | {int(r.n_test)} | "
            f"{r.median_max_tanimoto_test_to_train:.3f} | {dl} |")
    add("")
    sc = sp.loc["scaffold"]
    add(f"Scaffold splitting costs {100*(sc.test_mae-base)/base:.1f}% while "
        "cutting median nearest-neighbour similarity from "
        f"{sp.loc['random','median_max_tanimoto_test_to_train']:.3f} to "
        f"{sc.median_max_tanimoto_test_to_train:.3f}. This is the direct "
        "answer to the reviewer's concern about near-duplicates spanning the "
        "split: the effect exists and is modest.")
    add("")
    add("<sub>Source: `runs/revision2/B5_split_protocols.csv`</sub>")
    add("")
    add("---")
    add("")

    # ------------------------------------------------------------- Table 9
    add(f"## 8. Table {9} — {TABLES[9]}")
    add("")
    cols = list(t9.columns)
    add("| " + " | ".join(cols) + " |")
    add("|" + "---|" * len(cols))
    for _, r in t9.iterrows():
        add("| " + " | ".join(str(r[c]) for c in cols) + " |")
    add("")
    add("**All timings are single-threaded on one machine (Apple M4 Pro, 12 "
        "logical cores).** The submitted manuscript compared a SLURM DFT time "
        "against a laptop inference time; that cross-hardware comparison has "
        "been replaced. Re-timing on the same machine did not materially "
        "change the DFT figure, so the conclusion stands — but the caption "
        "must now state the hardware.")
    add("")
    add("⚠️ **Do not quote a single speedup.** Across the five "
        "representatives it spans roughly three orders of magnitude, because "
        "B3LYP cost grows steeply with system size while rCEG inference is "
        "essentially flat. Quote the range, or a named domain.")
    add("")
    add("<sub>Source: `runs/revision2/C3_timings.csv`; independent n=20 DFT "
        "timing in `T1_timing_dft_local.csv`</sub>")
    add("")
    add("---")
    add("")

    # -------------------------------------------------- reviewer-driven new
    add("## 9. New results answering specific reviewer objections")
    add("")
    add("### 9.1 \"The model is not structure-only\" (Reviewer 4)")
    add("")
    add("| Configuration | features | MAE (eV) | Δ vs full |")
    add("|---|---|---|---|")
    for cfg in ["full", "drop_x0_x4", "drop_x2_x4"]:
        if cfg not in b6.index:
            continue
        r = b6.loc[cfg]
        d = "—" if cfg == "full" else f"{r.delta_vs_full:+.4f} ({r.pct_worse:+.1f}%)"
        add(f"| `{cfg}` | {int(r.n_features)} | {r.mae:.4f} ± {r.mae_sd:.3f} "
            f"| {d} |")
    add("")
    if "drop_x0_x4" in b6.index:
        d = b6.loc["drop_x0_x4"]
        add(f"**The objection is answerable.** Removing all five PQR scalars "
            f"changes test MAE by {d.delta_vs_full:+.4f} eV "
            f"({d.pct_worse:+.1f}%), far inside the "
            f"±{b6.loc['full'].mae_sd:.3f} eV split-to-split SD. Inference on "
            "a new molecule needs only its SMILES string.")
    add("")
    add("Caveat that must travel with the claim: training labels are "
        "calibrated pseudo-labels derived from `pqr_gap`, a semiempirical "
        "quantity. The result licenses a statement about **inference**, not "
        "about training. Full detail in SI §S10.")
    add("")

    add("### 9.2 Geometry sensitivity")
    add("")
    add(f"| Quantity | Value |")
    add("|---|---|")
    add(f"| Molecules attempted | {len(geo)} |")
    add(f"| Converged | **{len(ok)}** |")
    add(f"| Mean &#124;Δ gap&#124; | **{ga.mean():.3f} eV** |")
    add(f"| Median &#124;Δ gap&#124; | **{ga.median():.3f} eV** |")
    add(f"| SD / max | {ga.std(ddof=1):.3f} / {ga.max():.3f} eV |")
    add("")
    add(f"⚠️ **This is the most consequential new number in the revision.** "
        f"The mean geometry-induced shift ({ga.mean():.3f} eV) **exceeds the "
        f"model's own test MAE ({fa.test_mae:.3f} eV)**. Two things follow:")
    add("")
    add("1. Accuracy should be quoted to **one decimal place** — 0.3 eV, not "
        "0.338 eV. The third digit is not meaningful when the choice of input "
        "geometry moves the answer by more than the error itself.")
    add("2. The paper must state that its accuracy is conditional on the "
        "UFF-optimized geometry the pipeline consumes.")
    add("")
    add(f"Only {len(ok)} of {len(geo)} optimizations converged, and the "
        "failures bias the estimate in both directions (SI §S7.2). Report "
        "with sample size and caveats attached.")
    add("")

    add("### 9.3 Conformational floor")
    add("")
    add(f"Median within-molecule gap SD across "
        f"{int(cf.n_molecules_ge3_conformers):,} molecules with ≥3 "
        f"conformers: **{cf.median_conformer_sd_eV:.3f} eV** "
        f"(IQR {cf.iqr_low:.3f}–{cf.iqr_high:.3f}). This is irreducible noise "
        "for any model that sees one conformer.")
    add("")

    add("### 9.4 Cross-protocol label floor")
    add("")
    add(f"On the {len(a8)} molecules labelled under both QM9 and Psi4 "
        f"protocols, mean absolute disagreement is "
        f"**{a8.abs_diff.mean():.3f} eV** (median {a8.abs_diff.median():.3f}, "
        f"max {a8.abs_diff.max():.3f}). The manuscript's 0.295 eV is "
        "confirmed. Two defensible reference protocols disagree by about the "
        "same amount as the model's error, which bounds what any model "
        "trained on the mixture can achieve.")
    add("")

    add("### 9.5 Reference pool arithmetic (Reviewer 2)")
    add("")
    add("1,228 QM9-overlap + 909 Psi4-recomputed − 14 dual-labelled = "
        "**2,123**, consistent with the split sizes 1,274 + 425 + 424 "
        "(identical in all ten repeats; membership varies, sizes do not). "
        "⚠️ **The manuscript's 2,137 is wrong** and appears in several "
        "places; all must be corrected.")
    add("")

    add("### 9.6 Leakage audit")
    add("")
    add(f"All {leak.feature.nunique()} features against four leakage-relevant "
        f"targets: largest absolute correlation anywhere is "
        f"**|r| = {leak.abs_corr.max():.3f}**, and "
        f"**{leak[leak.abs_corr>0.5].feature.nunique()} features** exceed "
        "|r| = 0.5. None approaches the |r| = 0.94 excision threshold. Full "
        "table in SI §S3.")
    add("")

    add("### 9.7 Open-shell agreement")
    add("")
    op = osh[osh.subset.str.contains("open-shell")].iloc[0]
    cs = osh[osh.subset.str.contains("neutral closed-shell")].iloc[0]
    add(f"PQR and DFT agree poorly on open-shell molecules: "
        f"r = **{op.pearson_r:.3f}** over {int(op.n)} molecules, against "
        f"r = {cs.pearson_r:.3f} for {int(cs.n)} neutral closed-shell "
        "molecules. This is the mechanism behind `charged_or_radical` being "
        "the weakest domain — a property of the input data, not of the "
        "learner, which is a stronger position for the paper than it sounds.")
    add("")
    add("⚠️ The submitted draft cites \"0.2 eV\" in this context. That value "
        f"matches no quantity computed here (the mean absolute difference is "
        f"{op.mean_abs_diff_eV:.1f} eV). See `DISCREPANCIES.md`.")
    add("")

    add("### 9.8 Descriptor identity and interpretability")
    add("")
    add(f"All {len(names)} LASSO-block descriptor names were recovered. "
        f"⚠️ **{int(mg.sum())} of them ({100*mg.mean():.0f}%) are Morgan "
        "fingerprint bits**, not named physicochemical descriptors. Any claim "
        "that the selected feature set is chemically interpretable must be "
        "narrowed accordingly.")
    add("")
    pmap = read(R2 / "A4_piecewise_feature_map.csv")
    n_mg_split = int(pmap.is_morgan_bit.sum()) if "is_morgan_bit" in pmap else 0
    add(f"The defensible interpretability claim is narrower and survives: "
        f"**{n_mg_split} of the 5 learned breakpoints falls on a Morgan "
        "bit** — all five are named descriptors (TPSA, Hall–Kier alpha, "
        "BCUT2D, Ipc, VSA_EState). SI §S5.")
    add("")

    add("### 9.9 External validation on QMugs")
    add("")
    add(f"| Evaluation | MAE (eV) | R² |")
    add("|---|---|---|")
    s0 = strict[strict.model == fa.frozen_architecture]
    c0 = cross[cross.model == fa.frozen_architecture]
    if not s0.empty:
        add(f"| strict frozen transfer | {s0.mae.iloc[0]:.3f} | "
            f"{s0.r2.iloc[0]:.2f} |")
    if not c0.empty:
        add(f"| 5-fold cross-fit, offset-aligned | **{c0.mae.iloc[0]:.3f}** | "
            f"{c0.r2.iloc[0]:.3f} |")
    add("")
    add(f"On {int(strict.n.iloc[0]):,} held-out QMugs molecules, excised by "
        "SMILES before fitting. Applied frozen the model does not transfer; "
        "once the protocol offset is estimated on held-out folds it reaches "
        f"{c0.mae.iloc[0]:.3f} eV. The honest reading — which should be "
        "stated as a limitation — is that rCEG transfers in ranking and "
        "shape but not in absolute placement, and a new reference protocol "
        "needs a handful of labelled anchors to re-align.")
    add("")
    add("---")
    add("")

    # ------------------------------------------------------ paste fragments
    add("## 10. Paste-ready fragment index")
    add("")
    add("Each file in `runs/revision2/paste/` is a self-contained Markdown "
        "block written to be dropped into the manuscript or the response to "
        "reviewers with minimal editing.")
    add("")
    add("| Fragment | Content | Manuscript destination |")
    add("|---|---|---|")
    DEST = {
        "A3_method_name.md": ("Semiempirical method identification",
                              "Methods — see DISCREPANCIES, unresolved"),
        "A6_openshell.md": ("Open-shell PQR/DFT agreement",
                            "Results — domain analysis; response to reviewers"),
        "A7_decision.md": ("Zero-gap contamination audit",
                           "Response to reviewers; Figure 1 caption"),
        "A8_pool_arithmetic.md": ("Reference pool arithmetic and label floor",
                                  "Methods — reference data; corrects 2,137"),
        "A9_scf_settings.md": ("Psi4 SCF and basis settings",
                               "Methods — reference calculations; SI §S6.3"),
        "B2_error_deciles.md": ("Per-domain error deciles",
                                "SI §S9; Results — Table 7 discussion"),
        "B4_domain_independence.md": ("Domain-dependence of the PQR offset",
                                      "Results — calibration; Table 4"),
        "B6_structure_only.md": ("Structure-only ablation",
                                 "Results — new subsection; SI §S10"),
        "C2_conformer_floor.md": ("Conformational noise floor",
                                  "Discussion — limits of accuracy"),
        "C3_table9.md": ("Per-domain computational cost",
                         "Table 9"),
        "T1_dft_timing.md": ("Same-hardware DFT reference timing",
                             "Table 9 caption; Methods — timing"),
    }
    for f in sorted(DEST):
        p = R2 / "paste" / f
        if not p.exists():
            add(f"| `{f}` | ⚠️ MISSING | — |")
            continue
        what, where = DEST[f]
        add(f"| `{f}` | {what} | {where} |")
    extra = sorted(p.name for p in (R2 / "paste").glob("*.md")
                   if p.name not in DEST)
    for f in extra:
        add(f"| `{f}` | (not in index — check before use) | — |")
    add("")
    add("---")
    add("")

    # ----------------------------------------------------------- file index
    add("## 11. Result file index")
    add("")
    add("| File | Contents |")
    add("|---|---|")
    IDX = {
        "A1_recompute_reconciliation.csv": "Recompute targeted/converged/failed by domain",
        "A1_recompute_failure_modes.csv": "Failure mode counts",
        "A2_cleaning_counts.csv": "Cleaning waterfall, closes to 21,923",
        "A2_stage1_valence_breakdown.csv": "Valence-rejection detail",
        "A4_lasso_feature_names.csv": "375 recovered descriptor names",
        "A4_piecewise_feature_map.csv": "The 5 split features, named",
        "A5_leakage_audit.csv": "Feature-target correlations, 1,708 rows",
        "A6_openshell_agreement.csv": "PQR/DFT agreement by charge and multiplicity",
        "A7_zero_gap_records.csv": "Zero-gap contamination check (empty = clean)",
        "A8_dual_labelled.csv": "14 molecules with both reference labels",
        "B2_table3.csv": "Per-domain performance → **manuscript Table 7**",
        "B2_error_deciles.csv": "Error percentiles by domain",
        "B3_ablation.csv": "Ablation summary → **Table 6**",
        "B3_ablation_per_seed.csv": "Ablation, per repeat",
        "B4_table5.csv": "Calibration by domain → **manuscript Table 4**",
        "B4_domain_independence_test.csv": "Offset by domain, held-out reference",
        "B5_split_protocols.csv": "Random/scaffold/cluster → **Table 8**",
        "B6_structure_only.csv": "Structure-only ablation, per repeat",
        "B6_summary.csv": "Structure-only ablation, summary",
        "C1_geometry_shift.csv": "Geometry sensitivity, per molecule",
        "C1_geometry_by_domain.csv": "Geometry sensitivity by domain",
        "C2_conformer_floor.csv": "Conformational noise floor",
        "C3_timings.csv": "Per-domain cost → **Table 9**",
        "C3_timings_qc.csv": "Timing raw measurements",
        "D1_external_metrics.csv": "QMugs external validation",
        "D1_external_by_domain.csv": "QMugs, per domain",
        "T1_timing_dft_local.csv": "Same-hardware DFT timing, n=20",
    }
    for f, what in IDX.items():
        mark = "" if (R2 / f).exists() else " ⚠️ MISSING"
        add(f"| `{f}`{mark} | {what} |")
    add("")
    add("---")
    add("")
    add("## 12. Provenance")
    add("")
    add("Every number above comes from `runs/rceg_final_consolidated/` or "
        "from `runs/revision2/`, which derives from it. The pre-patch "
        "directories (`*_LEAK094`) are provenance only and must not be cited. "
        "`runs/rceg_final_consolidated/headline_metrics.csv` **predates the "
        "final ten-repeat run and is stale** — it reports 0.318 eV, which is "
        "not the headline number. Do not read from it; it is retained only "
        "for audit history.")
    add("")
    add("All runs set `PYTHONHASHSEED=0`. Reruns were verified "
        "byte-identical. Environment captured in "
        "`runs/rceg_final_consolidated/environment_manifest.txt`.")
    add("")

    OUT.write_text("\n".join(L) + "\n")
    print(f"wrote {OUT}  ({len(L)} lines)")


if __name__ == "__main__":
    main()
